routes/web.php
<?php
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/clear-cache', function () {
   \Artisan::call('optimize:clear');
    return 'All cleared.';
});

Route::get('/', 'PageController@index')->name('home');
Route::get('getcoupons', 'CouponController@getcoupons');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::redirect('/home', '/');

Route::redirect('/admin', '/');

Route::get('register/verify/{confirmationCode}', 'UserDashboardController@confirm');

// Searching Routes
Route::get('search', 'SearchController@homeSearch');
Route::get('filtersearch', 'SearchController@filterSearch');
Route::get('homefilter', 'SearchController@filter');
Route::get('allfilter', 'SearchController@allfilter');
Route::get('blogsearch', 'SearchController@blogSearch');


Route::get('home-list', 'PageController@list_show');
Route::get('category', 'PageController@category_show');
Route::get('category-dtl/{slug}', 'PageController@cat_dtl_show');
Route::get('coupon', 'PageController@coupon_show');
Route::get('coupon-dtl/{slug}', 'PageController@coupon_dtl_show');
Route::get('forum', 'PageController@forum_show');
Route::get('deal-dtl/{slug}', 'PageController@deal_dtl_show');
Route::get('deal', 'PageController@deal_show');
Route::get('discussion', 'PageController@discussion_show');
Route::get('discussion-dtl/{$slug}', 'PageController@forum_dtl_show');
Route::get('forum-dtl/{slug}', 'PageController@forum_dtl_show');
Route::get('post/{uniID}/{slug}', 'PageController@post_show')->name('postpage');
Route::get('store', 'PageController@store_show');
Route::get('store-dtl/{slug}', 'PageController@store_dtl_show');
// Route::get('faq', 'PageController@faq_show');
Route::get('tag/{slug}', 'PageController@tag_show');
Route::get('blog', 'PageController@blog_show');
Route::get('blog-dtl/{uniId}/{slug}', 'PageController@blog_dtl_show');
Route::get('contact', 'PageController@contact_show')->name('contact');
Route::post('contact', 'PageController@contact_post');
Route::get('sell', 'PageController@sell_show');
Route::get('selling-policies', 'PageController@sell_policy_show');
Route::get('grow-bussiness', 'PageController@grow_show');
Route::get('counter', 'PageController@post_counter');
Route::post('sell/ajax_request', 'AjaxController@index')->name('ajax-route');
Route::post('contact/ajax_request', 'AjaxController@contact_inquiry')->name('contact-route');
Route::get('sendhtmlemail','MailController@html_email');
// Route::get('state','PageController@state');
Route::get('ajax/city','PageController@city');
// Route::get('get-city-list','PageController@getCityList');
Route::get('profile/{id}', 'PageController@profile_show');


// Admin Dashboard Routes
Route::group(['middleware' => ['web','auth','is_admin']], function(){
	Route::get('/admin','AdminDashboardController@dashboard_show');
	Route::get('admin/profile', function(){
    $auth = Auth::user();
    return view('admin.profile', compact('auth'));
  });
	Route::post('admin/profile-update', 'AdminDashboardController@update_profile');
  Route::resource('admin/category', 'CategoryController');
  Route::get('admin/send-notification', 'NotificationController@index');
  Route::get('admin/send-mail', 'NotificationController@mail');
	Route::post('admin/send-mail', 'NotificationController@mailsend');
  Route::post('admin/send-notification', 'NotificationController@sendmail');
  Route::post('admin/category/bulk_delete', 'CategoryController@bulk_delete');
	Route::resource('admin/store', 'StoreController');
  Route::post('admin/store/bulk_delete', 'StoreController@bulk_delete');
	Route::resource('admin/forumcategory', 'ForumCategoryController');
  Route::post('admin/forumcategory/bulk_delete', 'ForumCategoryController@bulk_delete');
	Route::resource('admin/discussion', 'DiscussionController');
  Route::post('admin/discussion/bulk_delete', 'DiscussionController@bulk_delete');
	Route::resource('admin/coupon', 'CouponController');
  Route::post('admin/coupon/bulk_delete', 'CouponController@bulk_delete');
  Route::get('dropdown', 'CouponController@dropdown');
	// Route::resource('admin/deal', 'DealController');
 //  Route::post('admin/deal/bulk_delete', 'DealController@bulk_delete');
  Route::resource('admin/user', 'UserController');
  Route::post('admin/user/bulk_delete', 'UserController@bulk_delete');
  Route::resource('admin/faqcategory', 'FaqCategoryController');
  Route::post('admin/faqcategory/bulk_delete', 'FaqCategoryController@bulk_delete');
  Route::resource('admin/faq', 'FaqController');
  Route::post('admin/faq/bulk_delete', 'FaqController@bulk_delete');
  Route::resource('admin/city', 'CityController');
  Route::post('admin/city/bulk_delete', 'CityController@bulk_delete');
  Route::resource('admin/hear-record', 'HearController');
  Route::post('admin/hear-record/bulk_delete', 'HearController@bulk_delete');
  Route::resource('admin/state', 'StateController');
  
  Route::post('admin/state/bulk_delete', 'StateController@bulk_delete');
  Route::resource('admin/social', 'SocialController');
  Route::post('admin/social/bulk_delete', 'SocialController@bulk_delete');
  Route::get('admin/slider', 'AdminDashboardController@slider_show');
  Route::get('admin/slider_list', 'AdminDashboardController@slider_list');
  Route::patch('admin/slider_update/{id}', 'AdminDashboardController@slider_update');
  Route::DELETE('admin/slider_dlt/{id}', 'AdminDashboardController@slider_dlt');
  Route::resource('admin/sliders', 'AdminDashboardController');
  Route::post('admin/sliders/create', 'AdminDashboardController@slider_create');
  Route::get('admin/sliders/edit/{id}', 'AdminDashboardController@slider_edit');
  Route::get('admin/settings', 'SettingsController@general_show');
  Route::patch('admin/settings_update/{id}', 'SettingsController@general_update');
  Route::resource('admin/comment', 'CommentController');
  Route::post('admin/comment/status/{id}', 'CommentController@status_update');
  Route::post('admin/comment/bulk_delete', 'CommentController@bulk_delete');
  Route::resource('admin/tag', 'TagController');
  Route::post('admin/tag/bulk_delete', 'TagController@bulk_delete');
  Route::resource('admin/inquiry', 'InquiryController');

  Route::post('admin/inquiry/bulk_delete', 'InquiryController@bulk_delete');
  Route::resource('admin/contact-inquiry', 'ContactinquiryController');

  Route::post('admin/contact-inquiry/bulk_delete', 'ContactinquiryController@bulk_delete');

  // City

    Route::get('city', 'CityController@index');
    Route::get('city/add', 'CityController@add');
    Route::post('city/add', 'CityController@adddata');
    Route::get('city/edit/{id}', 'CityController@edit');
    Route::post('city/edit/{id}', 'CityController@editdata');
    Route::get('city/remove/{id}','CityController@remove');
    Route::post('city/removeMultiple','CityController@removeMultiple');
  
  
  Route::resource('admin/city', 'CityController');
  Route::post('admin/city/bulk_delete', 'CityController@bulk_delete');
  
  
  Route::resource('admin/blog', 'BlogController');
  Route::post('admin/blog/bulk_delete', 'BlogController@bulk_delete');
  Route::resource('admin/pages', 'PagesController');
  Route::post('admin/pages/bulk_delete', 'PagesController@bulk_delete');
});

// User Dashboard Routes
Route::group(['middleware' => 'auth'], function(){
	Route::get('user/profile-edit', 'UserDashboardController@profile_edit');
	Route::patch('user/profile-update/{id}', 'UserDashboardController@profile_update');
	Route::patch('user/profile-edit', 'UserDashboardController@change_password');	
});

// User Dashboard Routes
Route::group(['middleware' => ['auth','is_verified']], function(){
  Route::post('submit-coupon', 'UserDashboardController@coupon_post');  
  Route::post('submit-discussion', 'UserDashboardController@discussion_post');
  Route::get('user/account', 'UserDashboardController@dashboard_show'); 
  Route::post('profile/follow', 'UserDashboardController@follow_user')->name('user.follow');
  Route::post('post/like', 'UserDashboardController@post_like')->name('post.like');
  Route::get('submit', 'UserDashboardController@deal_submit');
  Route::post('post/write', 'UserDashboardController@comment_store')->name('post.write');
  // Route::post('post/count', 'UserDashboardController@post_counter')->name('post.counter');
});


// OAuth Routes
Route::get('auth/{provider}', 'Auth\AuthController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\AuthController@handleProviderCallback');

// Mail Subscription
Route::post('emailsubscribe', 'EmailSubscribeController@subscribe');

Route::get('{page}', 'PageController@page_show'); 

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    
    protected $table 		= "citiese";

	public function cat(){
		return $this->hasOne('App\State', 'id', 'parent');
	}

    
}

app/Http/Controllers/CityController.php
<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\City;
use App\State;

class CityController extends Controller
{
   
    // public function index(request $request){

    //     $query = City::latest();

    //     if( !empty( $request->title ) ) {
    //         $query->where('title', 'LIKE', '%'.$request->title.'%');
    //     }


    //     $lists1 = $query->paginate(20);        

    //     $data = compact( 'lists1' ); // Variable to array convert
    //     return view('admin.city.create', $data);
    // }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $city = City::with('cat')->get();
        
        return view('admin.city.index', compact('city'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    

    

   
    // public function add()
    // {
    //     //

    //     $states = State::get();
    //     $parentArr = [
    //         ''  => 'Select State'
    //     ];

    //     foreach($states as $c) {

    //         $parentArr[ $c->id ] = $c->state;
    //     }
    //     $data = compact('parentArr');
    //     return view('backend.inc.city.add',$data);
    // }
    public function create()
    {

    	$states = State::get();
        $parentArr = [
            ''  => 'Select State'
        ];

        foreach($states as $c) {

            $parentArr[ $c->id ] = $c->name;
        }
        return view('admin.city.create', compact('parentArr'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    
    // public function addData(Request $request)
    // {
    //     //
    //     $rules = [
    //         'title'             => 'required',            
    //             ];
    //         // $file = $request->file('image','image_hover');
        
           
    //     $request->validate( $rules );
    //     $obj = new City;
    //     $obj->title             = $request->title;
    //     $obj->slug              = $request->slug == '' ? Str::slug($request->title) : Str::lower($request->slug);
    //     $obj->parent            = $request->parent;
        
        
    //     // $obj->image  = $request->$file->getClientOriginalName();
        
    //     $obj->save();

    //     return redirect( url('admin-control/city/') )->with('success', 'Success! New record has been added.');
    // }
    public function store(Request $request)
    {
        //
        $rules = [
            'name'             => 'required',            
                ];
            // $file = $request->file('image','image_hover');
        
           
        $request->validate( $rules );
        $obj = new City;
        $obj->name             = $request->name;
        $obj->slug              = $request->slug == '' ? Str::slug($request->title) : Str::lower($request->slug);
        $obj->parent            = $request->parent;
        
        
        // $obj->image  = $request->$file->getClientOriginalName();
        
        $obj->save();

        return back()->with('added','Faq has been added');;
    }   

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
   
    public function edit(Request $request,$id)
    {
        //
        $edit = City::findOrFail( $id );
        $request->replace($edit->toArray());
        $request->flash();
        $states = State::get();
        $parentArr = [
            ''  => 'Select State'
        ];

        foreach($states as $c) {
            $parentArr[ $c->id ] = $c->name;
        }
        


        $lists1 = City::latest()->paginate(20);
        //
        

        

        return view('admin.city.edit',compact('lists1','edit','parentArr'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    
    
    public function update(Request $request, $id)
    {
        //
        $rules = [
            'name'          => 'required',
            
            
        ];
        $request->validate( $rules );
        

        $obj = City::findOrFail( $id );
        $obj->name           = $request->name;
        $obj->slug            = $request->slug == '' ? Str::slug($request->name) : Str::lower($request->slug);
        $obj->parent          = $request->parent;
        
        $obj->save();
        return redirect('admin/city')->with('updated','City has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

     

    public function destroy($id)
    {
        $remove = City::where('id',$id)->delete();

        return back()->with('deleted','Faq has been deleted');;
    }

    // public function removeMultiple(Request $request)
    // {
    //     $check = $request->check; // input type="checkbox" name="check[]"
    //     City::whereIn("id", $check)->delete(); // DELETE FROM news WHERE news_id IN (3,5,4)

    //     return redirect()->back()->with('success', 'Item(s) removed.');
    // }

     public function bulk_delete(Request $request)
    {
        $check = $request->check; // input type="checkbox" name="check[]"

        City::whereIn("id", $check)->delete(); // DELETE FROM news WHERE news_id IN (3,5,4)

        return redirect()->back()->with('success', 'Item(s) removed.');  
    }

   
}

resources/views/admin/city/create.blade.php
@extends('layouts.admin')
@section('content')
  <div class="admin-form-main-block mrgn-t-40">
    <h4 class="admin-form-text"><a href="{{url('admin/city')}}" data-toggle="tooltip" data-original-title="Go back" class="btn-floating"><i class="material-icons">reply</i></a> Add City</h4> 
    {!! Form::open(['method' => 'POST', 'action' => 'CityController@store', 'files' => true]) !!}
      <div class="row admin-form-block z-depth-1">
        <div class="col-md-12">
          
          <div class="form-group">
              {!! Form::label('name', 'City Name*') !!} - 
              {!! Form::text('name', null, ['class' => 'form-control', 'required']) !!}
              
          </div> 
          <div class="form-group">
              {!! Form::label('slug', 'City Slug*') !!} - 
              {!! Form::text('slug', null, ['class' => 'form-control']) !!}
              
              
          </div> 
          <div class="form-group">
              {{ Form::label('parent') }} - 
              {{ Form::select('parent', $parentArr, '', ['class' => 'form-control']) }}
              
              
              
          </div> 
           
          <div class="btn-group pull-right">
            <button type="reset" class="btn btn-info">Reset</button>
            <button type="submit" class="btn btn-success">Create</button>
          </div>
          <div class="clear-both"></div>
        </div>  
      </div>
    {!! Form::close() !!}
  </div>
@endsection

resources/views/admin/city/edit.blade.php
@extends('layouts.admin')
@section('content')
  <div class="admin-form-main-block mrgn-t-40">
    <h4 class="admin-form-text"><a href="{{url('admin/city')}}" data-toggle="tooltip" data-original-title="Go back" class="btn-floating"><i class="material-icons">reply</i></a> Edit City</h4> 
    {!! Form::open(['method' => 'POST', 'action' => 'CityController@store', 'files' => true]) !!}
      <div class="row admin-form-block z-depth-1">
        <div class="col-md-12">
          
          <div class="form-group">
              {!! Form::label('name', 'City Name*') !!} - 
              {!! Form::text('name', null, ['class' => 'form-control', 'required']) !!}
              
          </div> 
          <div class="form-group">
              {!! Form::label('slug', 'City Slug*') !!} - 
              {!! Form::text('slug', null, ['class' => 'form-control', 'required']) !!}
              
              
          </div> 
          <div class="form-group">
              {{ Form::label('parent') }} - 
              {{ Form::select('parent', $parentArr, '', ['class' => 'form-control']) }}
              
              
              
          </div> 
           
          <div class="btn-group pull-right">
            <button type="reset" class="btn btn-info">Reset</button>
            <button type="submit" class="btn btn-success">Create</button>
          </div>
          <div class="clear-both"></div>
        </div>  
      </div>
    {!! Form::close() !!}
  </div>
@endsection

resources/views/admin/city/index.blade.php
@extends('layouts.admin')
@section('content')
  <div class="content-main-block  mrg-t-40">
    <div class="admin-create-btn-block">
      <a href="{{route('state.create')}}" class="btn btn-danger btn-md">Add State</a>
      <!-- Delete Modal -->
      <a type="button" class="btn btn-danger btn-md" data-toggle="modal" data-target="#bulk_delete"><i class="material-icons left">delete</i> Delete Selected</a>   
      <!-- Modal -->
      <div id="bulk_delete" class="delete-modal modal fade" role="dialog">
        <div class="modal-dialog modal-sm">
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <div class="delete-icon"></div>
            </div>
            <div class="modal-body text-center">
              <h4 class="modal-heading">Are You Sure ?</h4>
              <p>Do you really want to delete these records? This process cannot be undone.</p>
            </div>
            <div class="modal-footer">
              {!! Form::open(['method' => 'POST', 'action' => 'StateController@bulk_delete', 'id' => 'bulk_delete_form']) !!}
                <button type="reset" class="btn btn-gray translate-y-3" data-dismiss="modal">No</button>
                <button type="submit" class="btn btn-danger">Yes</button>
              {!! Form::close() !!}
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="content-block box-body table-responsive">
      <table id="full_detail_table" class="table table-hover table-responsive">
        <thead>
          <tr class="table-heading-row">
            <th>
              <div class="inline">
                <input id="checkboxAll" type="checkbox" class="filled-in" name="checked[]" value="all" id="checkboxAll">
                <label for="checkboxAll" class="material-checkbox"></label>
              </div>#</th>
            <th>Name</th>
            <!-- <th>Slug</th>      -->
            <th>State</th>              
            <th>Timestamp</th>
            <th>Actions</th>
          </tr>
        </thead>
        @if (isset($city))
          <tbody>
            @foreach($city as $key => $item)
              <tr>
                <td>
                  <div class="inline">
                    <input type="checkbox" form="bulk_delete_form" class="filled-in material-checkbox-input" name="checked[]" value="{{$item->id}}" id="checkbox{{$item->id}}">
                    <label for="checkbox{{$item->id}}" class="material-checkbox"></label>
                  </div>
                  {{$key+1}}
                </td>
                
                <td>{{$item->name}}</td>
                <!-- <td>{{$item->slug}}</td> -->
                <td>{{$item->cat ? $item->cat->name : 'N/A'}}</td>
                <td>{{$item->created_at}}</td>
                <td>
                  <div class="admin-table-action-block">
                    <a href="{{route('state.edit', $item->id)}}" data-toggle="tooltip" data-original-title="Edit" class="btn-info btn-floating"><i class="material-icons">mode_edit</i></a>
                    <!-- Delete Modal -->
                    <button type="button" class="btn-danger btn-floating" data-toggle="modal" data-target="#{{$item->id}}deleteModal"><i class="material-icons">delete</i> </button>
                    <!-- Modal -->
                    <div id="{{$item->id}}deleteModal" class="delete-modal modal fade" role="dialog">
                      <div class="modal-dialog modal-sm">
                        <!-- Modal content-->
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <div class="delete-icon"></div>
                          </div>
                          <div class="modal-body text-center">
                            <h4 class="modal-heading">Are You Sure ?</h4>
                            <p>Do you really want to delete these records? This process cannot be undone.</p>
                          </div>
                          <div class="modal-footer">
                            {!! Form::open(['method' => 'DELETE', 'action' => ['StateController@destroy', $item->id]]) !!}
                                <button type="reset" class="btn btn-gray translate-y-3" data-dismiss="modal">No</button>
                                <button type="submit" class="btn btn-danger">Yes</button>
                            {!! Form::close() !!}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </td>
              </tr>
            @endforeach
          </tbody>
        @endif  
      </table>
      {{-- <div class="eloquent-pagination">
        {{ $cities->links() }}
      </div> --}}
    </div>
  </div>
@endsection